## Teste do modelo
Este notebook tem como objetivo testar o modelo salvo pelo joblib.

In [14]:
import numpy as np
import joblib
import nltk
import re

In [17]:
#Baixando as stopwords
nltk.download('stopwords')

#Definindo o pré-processador para o vetorizador
def preprocessador(instancia):
  #Removendo stopwords
  stopwords = set(nltk.corpus.stopwords.words('portuguese'))
  stopwords.remove('não')

  #Removendo caracteres indesejados
  instancia = [p.lower() for p in instancia.split() if p.lower() not in stopwords]
  instancia = " ".join(instancia)

  instancia = re.sub("[,.;/\[\]?!\'\"]", '', instancia)
  return instancia

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [18]:
model = joblib.load('modelo/model.sav)

In [19]:
#Frases customizadas
frases = ['Não quero te ver nunca mais', #raiva
          'Eu amo minha vida', #felicidade
          'Sempre estou sozinho', #tristeza
          'Ainda bem que encontrei dinheiro na rua'] #felicidade

proba = model.predict_proba(frases)

classes = ['felicidade', 'raiva', 'tristeza']
print(f'\n\nSVC:\nClassificações: {[classes[i] for i in np.argmax(proba, axis=1)]}\nProbabilidades: {proba}')



SVC:
Classificações: ['raiva', 'felicidade', 'tristeza', 'felicidade']
Probabilidades: [[0.29358974 0.3692684  0.33714185]
 [0.47574517 0.23278279 0.29147204]
 [0.0915514  0.08156315 0.82688546]
 [0.83739618 0.14357874 0.01902508]]


O modelo realizou as predições com sucesso, e tendo capacidade de efetivar predições com um bom nível de confiança